CREATE USER PARKING IDENTIFIED BY masterkey;

GRANT CONNECT TO PARKING;

GRANT CREATE SESSION TO PARKING;

GRANT CREATE TABLE TO PARKING;

GRANT CREATE SEQUENCE TO PARKING;

ALTER USER PARKING QUOTA UNLIMITED ON USERS;